WIP - Initial Prototype of AutoML Visualizer
colombod/dotnet-interactive-extension-lab pull request #10
Opened 2022-03-29 23:47 UTC by JakeRadMSFT

2022-03-30 11:20 UTC, colombod commented on src/MLNetAutoML.InteractiveExtension/MLNetAutoML.InteractiveExtension.csproj
> +		<PackageReference Include="Microsoft.ML.AutoML" Version="0.20.3-dev.22174.1" />
This package is missing in nuget.org

2022-03-30 11:21 UTC, colombod commented on src/MLNetAutoML.InteractiveExtension/MLNetAutoML.InteractiveExtension.csproj
> +		<PackageReference Include="XPlot.Plotly" Version="4.0.1" />
should use plotyl.net

2022-03-30 11:24 UTC, colombod commented on src/MLNetAutoML.InteractiveExtension/KernelExtension.cs
> +            Formatter.GetPreferredFormatterFor(typeof(PlotlyChart), "text/html").Format(chart, writer);
@jonsequitur this could fail if the extension (xplot or plotly) is not explicitly loaded. The formatter could not be loaded

2022-05-17 20:55 UTC, colombod requested changes

2022-05-17 20:55 UTC, colombod commented on src/MLNetAutoML.InteractiveExtension/KernelExtension.cs
> +using XPlot.Plotly;
can we use plotly.net instead of xplot

2022-05-17 20:58 UTC, colombod commented on src/MLNetAutoML.InteractiveExtension/KernelExtension.cs
> +        public async Task OnLoadAsync(Kernel kernel)
this one can drop async and just return Task.Completed

2022-05-17 21:00 UTC, jonsequitur commented on src/MLNetAutoML.InteractiveExtension/KernelExtension.cs
> +namespace MLNetAutoML.InteractiveExtension
Should the namespace match the existing AutoML namespaces?

2022-06-14 20:16 UTC, JakeRadMSFT commented on src/MLNetAutoML.InteractiveExtension/MLNetAutoML.InteractiveExtension.csproj
> +		<PackageReference Include="Microsoft.ML.AutoML" Version="0.20.3-dev.22174.1" />
Resolved!

2022-06-14 20:18 UTC, JakeRadMSFT commented on src/MLNetAutoML.InteractiveExtension/KernelExtension.cs
> +namespace MLNetAutoML.InteractiveExtension
Is that the guidance?

2022-06-14 20:20 UTC, JakeRadMSFT commented
FYI -  We'll probably move this to machinelearning repo once Plotly.NET is signed.

2022-07-06 21:28 UTC, closed without merging